# Use NVIDIA PyTorch base image
FROM nvcr.io/nvidia/pytorch:24.11-py3

# Add labels for metadata
LABEL Maintainer="P9-Energy" \
      Project="P9 Energy Container"

# Install additional dependencies
RUN echo "Installing P9 Energy dependencies" && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install pandas numpy scikit-learn statsmodels matplotlib seaborn prophet optuna neuralforecast pytorch_forecasting && \
    echo "P9 Energy dependencies installed"

# Test the setup
RUN echo "Testing P9 Energy Container" && \
    python3 --version && \
    pip3 --version && \
    echo "P9 Energy Container is ready to use"

# Set the default command to execute when the container starts
CMD ["bash"]
